
GET http://localhost:8080/employees
###
POST http://localhost:8080/employees
Content-Type: application/json

{"name":"TestName",
 "surName":"surNameTest",
"departament": 1,
  "salary": 1000
}
###
POST http://localhost:8080/employees
Content-Type: application/json

{"name":"TestName2",
  "surName":"surNameTest2",
  "departament": 2,
  "salary": 3000
}
