
GET http://localhost:8080/employees/get
### Ввод первого сотрудника
POST http://localhost:8080/employees/add
Content-Type: application/json

{"name":"estName",
 "surName":"ввп",
"departament": 1,
  "salary": 1000
}
### Ввод второго сотрудника
POST http://localhost:8080/employees/add
Content-Type: application/json

{ "name": "dfy",
  "surName":"surNameTest",
  "departament": 2,
  "salary": 3000
}
### Вывод суммы зарплаты
GET http://localhost:8080/employees/salary/sum
### Вывод сотрудника с минимальной зп
GET http://localhost:8080/employees/salary/min

### Вывод сотрудника с максимальной зп
GET http://localhost:8080/employees/salary/max
### Сотрудники (только фамилии)у которых з/п больше средней
GET http://localhost:8080/employees/salary/sred

### Сотрудники (полностью объект)у которых з/п больше средней
GET http://localhost:8080/employees/salary/sre1